### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by Jadentan** [nilboy/gaic_track3_pair_sim#2]
天池网站的数据已经无法获取，可否给一个链接获取比赛数据

**Comment by nilboy** [comment]
https://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531851/round2_20210407/gaiic_track3_round2_train_20210407.zip

**Comment by soundmemories** [comment]
> https://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531851/round2_20210407/gaiic_track3_round2_train_20210407.zip
此数据是id构成，缺少对应vocab词表，请问能给一份对应的vocab词表吗？谢谢！
