### ISSUE TITLE
软标签

### ISSUE THREAD

**Issue by Tongjilibo** [nilboy/gaic_track3_pair_sim#5]
方案一中train.sh中，先预训练M个模型，然后训练M*K个kfold分类模型，并用这些分类模型对kfold数据打标签，得到classification的soft label的训练数据A。然后用ensemble模型，训练数据A训练kfold回归模型，然后再给kfold数据打标签，然后得到regression的soft label的训练数据B，然后在用ensemble模型，训练数据B训练全量回归模型。
请教下为什么要打两次softlabel标签呢？基于分类模型来预测的softlabel，直接训练一次回归模型可以吗

**Comment by nilboy** [comment]
可以的，没有太大差别，做多次会有略微提升。
