### ISSUE TITLE
代码方案请教

### ISSUE THREAD

**Issue by rookiebird** [nilboy/gaic_track3_pair_sim#6]
感谢大佬开源方案，一边看代码一边跑从中学习了很多， 有些两个问题想要请教一下：
1. 初赛的时候，最终训练的模型是回归模型， 这种做法有在哪个论文里面有提到过吗？ 还是只是比赛的一种trick
2. 为什么初赛，复赛，复赛b榜的方案都不一样呢？ 感觉上做法是越做越简单了， 最后定榜的模型直接是多个分类模型的average, 为什么之前的方法(构建soft label 训练regresssion model 和 构建大的ensemble 模型的方法没有继续沿用了呢？ )

如果大佬还记得相关的细节，麻烦指导下，再次谢谢

**Comment by nilboy** [comment]
1. 不知道有没有具体的论文提过。参考的是类似于模型蒸馏的思想。
2. 初赛训练数据量相对较小，所以需要较多的方法提升模型对数据的利用效率；复赛数据量增加，其实之前的一些方法很多都没什么收益了。复赛a榜的大模型做法纯粹是个人想尝试通过这种单个模型端到端能否实现较好的效果。

**Comment by rookiebird** [comment]
感谢， 用回归任务做蒸馏的目标的论文我去找找看看。 还有一个问题： 看你的代码，才了解到wandb这个工具的， 那你是第一名，在参加比赛的时候，有花很多时间去调超参数吗？ 因为现在模型确实越来越大了，算力不够的时候，超参数的调整时间会花的非常长， 我自己学习的过程中，得到的告诫是把数据处理的更好，才能把模型效果提升上来，但是我现在也很疑惑，现在像bert这样的大预训练模型，还需要去费精力去调整超参数吗？

**Comment by nilboy** [comment]
我个人的经验是，通过经验设的超参数往往有比较好的效果。我自己在使用wandb去做超参搜索并没有得到额外的收益。（当然超参还是很重要的，如果你没有很多经验，还是可以用类似的工具去做搜索）
